package com.company.platform.administration.application;

import com.company.platform.administration.infrastructure.TenantContextProvider;
import java.math.BigDecimal;
import java.time.Instant;
import java.util.*;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.core.Authentication;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
public class CatalogAdministrationService {
    private final JdbcTemplate jdbc; private final TenantContextProvider context;
    public CatalogAdministrationService(JdbcTemplate jdbc,TenantContextProvider context){this.jdbc=jdbc;this.context=context;}
    private boolean platform(Authentication a){return a!=null&&a.getAuthorities().stream().anyMatch(x->Set.of("PLATFORM_ADMIN","ROLE_PLATFORM_ADMIN").contains(x.getAuthority()));}
    private boolean editor(Authentication a){return platform(a)||(a!=null&&a.getAuthorities().stream().anyMatch(x->Set.of("TENANT_OWNER","ROLE_TENANT_OWNER","TENANT_ADMIN","ROLE_TENANT_ADMIN").contains(x.getAuthority())));}
    private UUID scope(Authentication a,Map<String,Object>b){if(!editor(a))throw new SecurityException("administration write permission required");if(platform(a)&&b.get("tenantId")!=null)return uuid(b,"tenantId");return context.currentTenantId();}
    private UUID readScope(Authentication a,UUID requested){if(platform(a)&&requested!=null)return requested;UUID t=context.currentTenantId();if(requested!=null&&!requested.equals(t))throw new SecurityException("cross-tenant access denied");return t;}
    private UUID uuid(Map<String,Object>b,String k){Object v=b.get(k);if(v==null)throw new IllegalArgumentException(k+" is required");return UUID.fromString(v.toString());}
    private String str(Map<String,Object>b,String k){Object v=b.get(k);if(v==null||v.toString().isBlank())throw new IllegalArgumentException(k+" is required");return v.toString().trim();}
    private String opt(Map<String,Object>b,String k){Object v=b.get(k);return v==null?null:v.toString().trim();}
    private BigDecimal dec(Map<String,Object>b,String k){try{return new BigDecimal(str(b,k));}catch(NumberFormatException e){throw new IllegalArgumentException(k+" must be decimal");}}
    private Map<String,Object> one(String sql,Object...args){return jdbc.queryForList(sql,args).stream().findFirst().orElseThrow(()->new NoSuchElementException("resource not found"));}
    private String table(String type){return switch(type){case"companies"->"administration_companies";case"categories"->"administration_categories";case"taxes"->"administration_taxes";case"products"->"administration_products";case"services"->"administration_services";default->throw new IllegalArgumentException("unsupported resource");};}
    private String selection(String type){return type.equals("products")?"p.*,COALESCE((SELECT SUM(i.on_hand-i.reserved-i.committed-i.damaged) FROM inventory.inventory i WHERE i.tenant_id=p.tenant_id AND i.product_id=p.id),0) AS stock":"p.*";}
    public List<Map<String,Object>> list(String type,Authentication a,UUID tenantId,String search,int page,int size){UUID t=readScope(a,tenantId);String expression=switch(type){case"companies"->"p.legal_name||' '||p.commercial_name";case"products"->"p.name||' '||p.sku";case"services","taxes"->"p.name||' '||p.code";default->"p.name";};String q="SELECT "+selection(type)+" FROM "+table(type)+" p WHERE p.tenant_id=?"+(type.equals("products")?" AND p.deleted_at IS NULL":"")+" AND (?='' OR LOWER("+expression+") LIKE ?) ORDER BY p.created_at DESC LIMIT ? OFFSET ?";int limit=Math.min(Math.max(size,1),100);String s=search==null?"":search.trim().toLowerCase();return jdbc.queryForList(q,t,s,"%"+s+"%",limit,Math.max(page,0)*limit);}
    public Map<String,Object> get(String type,UUID id,Authentication a){if(platform(a))return one("SELECT "+selection(type)+" FROM "+table(type)+" p WHERE p.id=?"+(type.equals("products")?" AND p.deleted_at IS NULL":""),id);UUID t=readScope(a,null);return one("SELECT "+selection(type)+" FROM "+table(type)+" p WHERE p.id=? AND p.tenant_id=?"+(type.equals("products")?" AND p.deleted_at IS NULL":""),id,t);}
    @Transactional public Map<String,Object> create(String type,Map<String,Object>b,Authentication a){UUID t=scope(a,b),id=UUID.randomUUID();Instant now=Instant.now();switch(type){
      case"companies"->jdbc.update("INSERT INTO administration_companies VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",id,t,str(b,"legalName"),str(b,"commercialName"),str(b,"taxId"),opt(b,"description"),opt(b,"email"),opt(b,"phone"),opt(b,"website"),opt(b,"address"),opt(b,"city"),opt(b,"country"),"ACTIVE",now,now);
      case"categories"->jdbc.update("INSERT INTO administration_categories VALUES(?,?,?,?,?,?,?)",id,t,str(b,"name"),opt(b,"description"),"ACTIVE",now,now);
      case"taxes"->jdbc.update("INSERT INTO administration_taxes VALUES(?,?,?,?,?,?,?,?)",id,t,str(b,"code"),str(b,"name"),dec(b,"rate"),"ACTIVE",now,now);
      case"products"->{UUID tax=b.get("taxId")==null?null:uuid(b,"taxId");BigDecimal amount=dec(b,"amount"),rate=tax==null?BigDecimal.ZERO:(BigDecimal)one("SELECT rate FROM administration_taxes WHERE id=? AND tenant_id=?",tax,t).get("rate");BigDecimal total=amount.add(amount.multiply(rate).movePointLeft(2));jdbc.update("INSERT INTO administration_products VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",id,t,uuid(b,"companyId"),uuid(b,"categoryId"),tax,str(b,"sku"),str(b,"name"),opt(b,"description"),opt(b,"shortDescription"),opt(b,"brand"),str(b,"unitOfMeasure"),amount,str(b,"currency").toUpperCase(),total,"DRAFT",now,now,null);}
      case"services"->{UUID tax=b.get("taxId")==null?null:uuid(b,"taxId");BigDecimal amount=dec(b,"amount"),rate=tax==null?BigDecimal.ZERO:(BigDecimal)one("SELECT rate FROM administration_taxes WHERE id=? AND tenant_id=?",tax,t).get("rate");jdbc.update("INSERT INTO administration_services VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)",id,t,uuid(b,"companyId"),tax,str(b,"code"),str(b,"name"),opt(b,"description"),amount,str(b,"currency").toUpperCase(),amount.add(amount.multiply(rate).movePointLeft(2)),"DRAFT",now,now);}
      default->throw new IllegalArgumentException("unsupported resource");}return get(type,id,a);}
    @Transactional public Map<String,Object> update(String type,UUID id,Map<String,Object>b,Authentication a){Map<String,Object> existing=get(type,id,a);UUID t=platform(a)?(UUID)existing.get("tenant_id"):readScope(a,null);if(!editor(a))throw new SecurityException("administration write permission required");switch(type){
      case"companies"->jdbc.update("UPDATE administration_companies SET legal_name=?,commercial_name=?,tax_id=?,description=?,email=?,phone=?,website=?,address=?,city=?,country=?,updated_at=now() WHERE id=? AND tenant_id=?",str(b,"legalName"),str(b,"commercialName"),str(b,"taxId"),opt(b,"description"),opt(b,"email"),opt(b,"phone"),opt(b,"website"),opt(b,"address"),opt(b,"city"),opt(b,"country"),id,t);
      case"categories"->jdbc.update("UPDATE administration_categories SET name=?,description=?,updated_at=now() WHERE id=? AND tenant_id=?",str(b,"name"),opt(b,"description"),id,t);
      case"taxes"->jdbc.update("UPDATE administration_taxes SET code=?,name=?,rate=?,updated_at=now() WHERE id=? AND tenant_id=?",str(b,"code"),str(b,"name"),dec(b,"rate"),id,t);
      case"products"->{UUID tax=b.get("taxId")==null?null:uuid(b,"taxId");BigDecimal amount=dec(b,"amount"),rate=tax==null?BigDecimal.ZERO:(BigDecimal)one("SELECT rate FROM administration_taxes WHERE id=? AND tenant_id=?",tax,t).get("rate");jdbc.update("UPDATE administration_products SET company_id=?,category_id=?,tax_id=?,sku=?,name=?,description=?,short_description=?,brand=?,unit_of_measure=?,amount=?,currency=?,final_price=?,updated_at=now() WHERE id=? AND tenant_id=?",uuid(b,"companyId"),uuid(b,"categoryId"),tax,str(b,"sku"),str(b,"name"),opt(b,"description"),opt(b,"shortDescription"),opt(b,"brand"),str(b,"unitOfMeasure"),amount,str(b,"currency").toUpperCase(),amount.add(amount.multiply(rate).movePointLeft(2)),id,t);if("ACTIVE".equals(existing.get("status")))syncMarketplace(id,t,"ACTIVE");}
      case"services"->{UUID tax=b.get("taxId")==null?null:uuid(b,"taxId");BigDecimal amount=dec(b,"amount"),rate=tax==null?BigDecimal.ZERO:(BigDecimal)one("SELECT rate FROM administration_taxes WHERE id=? AND tenant_id=?",tax,t).get("rate");jdbc.update("UPDATE administration_services SET company_id=?,tax_id=?,code=?,name=?,description=?,amount=?,currency=?,final_price=?,updated_at=now() WHERE id=? AND tenant_id=?",uuid(b,"companyId"),tax,str(b,"code"),str(b,"name"),opt(b,"description"),amount,str(b,"currency").toUpperCase(),amount.add(amount.multiply(rate).movePointLeft(2)),id,t);}
      default->throw new IllegalArgumentException("unsupported resource");}return get(type,id,a);}
    @Transactional public Map<String,Object> status(String type,UUID id,String status,Authentication a){Map<String,Object> existing=get(type,id,a);UUID t=platform(a)?(UUID)existing.get("tenant_id"):readScope(a,null);if(!editor(a))throw new SecurityException("administration write permission required");Set<String> allowed=type.equals("products")||type.equals("services")?Set.of("DRAFT","ACTIVE","INACTIVE"):Set.of("ACTIVE","INACTIVE");if(!allowed.contains(status))throw new IllegalArgumentException("invalid status");jdbc.update("UPDATE "+table(type)+" SET status=?,updated_at=now() WHERE id=? AND tenant_id=?",status,id,t);if(type.equals("products"))syncMarketplace(id,t,status);if(type.equals("companies")&&status.equals("INACTIVE")){jdbc.update("UPDATE administration_products SET status='INACTIVE',updated_at=now() WHERE company_id=? AND tenant_id=?",id,t);jdbc.update("UPDATE marketplace.products SET status='INACTIVE' WHERE tenant_id=? AND id IN (SELECT id FROM administration_products WHERE company_id=? AND tenant_id=?)",t,id,t);}return get(type,id,a);}
    private void syncMarketplace(UUID id,UUID tenant,String status){if(!"ACTIVE".equals(status)){jdbc.update("UPDATE marketplace.products SET status='INACTIVE' WHERE id=? AND tenant_id=?",id,tenant);jdbc.update("UPDATE commerce.sellable_products SET status='DISABLED',updated_at=now() WHERE marketplace_product_id=? AND tenant_id=?",id,tenant);jdbc.update("UPDATE commerce.prices SET status='INACTIVE',updated_at=now() WHERE sellable_product_id=? AND tenant_id=?",id,tenant);return;}Map<String,Object> p=one("SELECT * FROM administration_products WHERE id=? AND tenant_id=?",id,tenant);List<Map<String,Object>> catalogs=jdbc.queryForList("SELECT c.id catalog_id,c.store_id FROM marketplace.catalogs c JOIN public.stores s ON s.id=c.store_id WHERE c.tenant_id=? AND c.status='ACTIVE' AND s.status='ACTIVE' ORDER BY c.created_at LIMIT 1",tenant);if(catalogs.isEmpty())return;Map<String,Object> catalog=catalogs.get(0);UUID store=(UUID)catalog.get("store_id"),catalogId=(UUID)catalog.get("catalog_id");jdbc.update("INSERT INTO marketplace.products(id,tenant_id,store_id,catalog_id,category_id,sku,name,description,status,created_at,updated_at) VALUES(?,?,?,?,NULL,?,?,?,?,now(),now()) ON CONFLICT(id) DO UPDATE SET sku=EXCLUDED.sku,name=EXCLUDED.name,description=EXCLUDED.description,status='ACTIVE',updated_at=now()",id,tenant,store,catalogId,p.get("sku"),p.get("name"),p.get("description"),"ACTIVE");jdbc.update("INSERT INTO commerce.sellable_products(id,tenant_id,marketplace_product_id,store_id,status,created_at,updated_at) VALUES(?,?,?,?, 'ENABLED',now(),now()) ON CONFLICT(id) DO UPDATE SET status='ENABLED',updated_at=now()",id,tenant,id,store);jdbc.update("INSERT INTO commerce.prices(id,tenant_id,sellable_product_id,amount,currency,valid_from,valid_until,status,created_at,updated_at) VALUES(?,?,?,?,?,now(),now()+interval '10 years','ACTIVE',now(),now()) ON CONFLICT(id) DO UPDATE SET amount=EXCLUDED.amount,currency=EXCLUDED.currency,status='ACTIVE',updated_at=now()",id,tenant,id,p.get("amount"),p.get("currency"));}
    @Transactional public void deleteProduct(UUID id,Authentication a){Map<String,Object> p=get("products",id,a);UUID t=platform(a)?(UUID)p.get("tenant_id"):readScope(a,null);if(!editor(a))throw new SecurityException("administration write permission required");syncMarketplace(id,t,"INACTIVE");jdbc.update("UPDATE administration_products SET status='INACTIVE',deleted_at=now(),updated_at=now() WHERE id=? AND tenant_id=?",id,t);}
    public List<Map<String,Object>> images(UUID product,Authentication a){Map<String,Object> p=get("products",product,a);UUID t=platform(a)?(UUID)p.get("tenant_id"):readScope(a,null);return jdbc.queryForList("SELECT * FROM administration_product_images WHERE product_id=? AND tenant_id=? ORDER BY sort_order",product,t);}
    @Transactional public Map<String,Object> addImage(UUID product,Map<String,Object>b,Authentication a){Map<String,Object> p=get("products",product,a);UUID t=platform(a)?(UUID)p.get("tenant_id"):readScope(a,null);if(!editor(a))throw new SecurityException("administration write permission required");UUID id=UUID.randomUUID();boolean primary=Boolean.TRUE.equals(b.get("isPrimary"));if(primary)jdbc.update("UPDATE administration_product_images SET is_primary=false WHERE product_id=?",product);jdbc.update("INSERT INTO administration_product_images VALUES(?,?,?,?,?,?,?,?,?)",id,t,product,str(b,"url"),opt(b,"altText"),Integer.parseInt(String.valueOf(b.getOrDefault("sortOrder",0))),primary,"ACTIVE",Instant.now());return one("SELECT * FROM administration_product_images WHERE id=? AND tenant_id=?",id,t);}
    @Transactional public Map<String,Object> updateImage(UUID product,UUID image,Map<String,Object>b,Authentication a){Map<String,Object> p=get("products",product,a);UUID t=platform(a)?(UUID)p.get("tenant_id"):readScope(a,null);if(!editor(a))throw new SecurityException("administration write permission required");boolean primary=Boolean.TRUE.equals(b.get("isPrimary"));if(primary)jdbc.update("UPDATE administration_product_images SET is_primary=false WHERE product_id=?",product);jdbc.update("UPDATE administration_product_images SET url=?,alt_text=?,sort_order=?,is_primary=?,status=? WHERE id=? AND product_id=? AND tenant_id=?",str(b,"url"),opt(b,"altText"),Integer.parseInt(String.valueOf(b.getOrDefault("sortOrder",0))),primary,String.valueOf(b.getOrDefault("status","ACTIVE")),image,product,t);return one("SELECT * FROM administration_product_images WHERE id=? AND tenant_id=?",image,t);}
    @Transactional public void deleteImage(UUID product,UUID image,Authentication a){Map<String,Object> p=get("products",product,a);UUID t=platform(a)?(UUID)p.get("tenant_id"):readScope(a,null);if(!editor(a))throw new SecurityException("administration write permission required");jdbc.update("DELETE FROM administration_product_images WHERE id=? AND product_id=? AND tenant_id=?",image,product,t);}
    public List<Map<String,Object>> capabilities(){return jdbc.queryForList("SELECT * FROM administration_capabilities ORDER BY code");}
    public List<Map<String,Object>> tenantCapabilities(UUID tenant,Authentication a){readScope(a,tenant);return jdbc.queryForList("SELECT c.*,COALESCE(tc.status,'INACTIVE') tenant_status FROM administration_capabilities c LEFT JOIN administration_tenant_capabilities tc ON tc.capability_id=c.id AND tc.tenant_id=? ORDER BY c.code",tenant);}
    @Transactional public Map<String,Object> setCapability(UUID tenant,String code,String status,Authentication a){readScope(a,tenant);if(!editor(a))throw new SecurityException("administration write permission required");if(!Set.of("ACTIVE","INACTIVE").contains(status))throw new IllegalArgumentException("invalid status");UUID cap=(UUID)one("SELECT id FROM administration_capabilities WHERE code=? AND status='ACTIVE'",code).get("id");jdbc.update("INSERT INTO administration_tenant_capabilities VALUES(?,?,?,now(),now()) ON CONFLICT(tenant_id,capability_id) DO UPDATE SET status=EXCLUDED.status,updated_at=now()",tenant,cap,status);return one("SELECT c.code,tc.status FROM administration_tenant_capabilities tc JOIN administration_capabilities c ON c.id=tc.capability_id WHERE tc.tenant_id=? AND c.id=?",tenant,cap);}
}
