server {
  listen 80;
  root /usr/share/nginx/html;
  index index.html;
  location / { try_files $uri $uri/ /index.html; }
  location /api/ { proxy_pass http://marketplace-service:8099/; proxy_set_header Authorization $http_authorization; proxy_set_header X-Correlation-Id $http_x_correlation_id; }
  location /admin-api/ { proxy_pass http://administration-service:8095/api/admin/; proxy_set_header Authorization $http_authorization; proxy_set_header X-Correlation-Id $http_x_correlation_id; }
  location /integration-api/ { proxy_pass http://integration-service:8094/api/integrations/; proxy_set_header Authorization $http_authorization; proxy_set_header X-Correlation-Id $http_x_correlation_id; }
  location /analytics-api/ { proxy_pass http://analytics-service:8093/api/analytics/; proxy_set_header Authorization $http_authorization; proxy_set_header X-Correlation-Id $http_x_correlation_id; }
}
