package com.company.platform.payment.infrastructure;

import java.util.HashMap; import java.util.Map;
import org.apache.kafka.clients.producer.ProducerConfig; import org.apache.kafka.common.serialization.StringSerializer;
import org.springframework.context.annotation.*; import org.springframework.kafka.core.*; import org.springframework.kafka.support.serializer.JsonSerializer; import org.springframework.kafka.config.ConcurrentKafkaListenerContainerFactory; import org.springframework.kafka.support.serializer.JsonDeserializer; import org.springframework.kafka.listener.*; import org.springframework.kafka.core.KafkaTemplate; import org.springframework.util.backoff.FixedBackOff;

@Configuration
public class KafkaConfiguration {
    @Bean ProducerFactory<String,Object> producerFactory(){Map<String,Object> p=new HashMap<>();p.put(ProducerConfig.BOOTSTRAP_SERVERS_CONFIG,System.getenv().getOrDefault("KAFKA_BOOTSTRAP_SERVERS","localhost:9092"));p.put(ProducerConfig.KEY_SERIALIZER_CLASS_CONFIG,StringSerializer.class);p.put(ProducerConfig.VALUE_SERIALIZER_CLASS_CONFIG,JsonSerializer.class);return new DefaultKafkaProducerFactory<>(p);}
    @Bean KafkaTemplate<String,Object> kafkaTemplate(ProducerFactory<String,Object> factory){return new KafkaTemplate<>(factory);} @Bean ConcurrentKafkaListenerContainerFactory<String,com.fasterxml.jackson.databind.JsonNode> paymentKafkaListenerContainerFactory(org.springframework.kafka.core.ConsumerFactory<String,com.fasterxml.jackson.databind.JsonNode> consumerFactory,KafkaTemplate<String,Object> template){var f=new ConcurrentKafkaListenerContainerFactory<String,com.fasterxml.jackson.databind.JsonNode>();f.setConsumerFactory(consumerFactory);f.setCommonErrorHandler(new DefaultErrorHandler(new DeadLetterPublishingRecoverer(template),new FixedBackOff(1000L,2L)));return f;} @Bean org.springframework.kafka.core.ConsumerFactory<String,com.fasterxml.jackson.databind.JsonNode> consumerFactory(){Map<String,Object> p=new HashMap<>();p.put(org.apache.kafka.clients.consumer.ConsumerConfig.BOOTSTRAP_SERVERS_CONFIG,System.getenv().getOrDefault("KAFKA_BOOTSTRAP_SERVERS","localhost:9092"));p.put(org.apache.kafka.clients.consumer.ConsumerConfig.GROUP_ID_CONFIG,"payment-service");p.put(org.apache.kafka.clients.consumer.ConsumerConfig.KEY_DESERIALIZER_CLASS_CONFIG,org.apache.kafka.common.serialization.StringDeserializer.class);p.put(org.apache.kafka.clients.consumer.ConsumerConfig.VALUE_DESERIALIZER_CLASS_CONFIG,JsonDeserializer.class);p.put(JsonDeserializer.TRUSTED_PACKAGES,"*");return new org.springframework.kafka.core.DefaultKafkaConsumerFactory<>(p,new org.apache.kafka.common.serialization.StringDeserializer(),new JsonDeserializer<>(com.fasterxml.jackson.databind.JsonNode.class,false));}
}
