package com.company.platform.commerce.api;
import com.company.platform.commerce.domain.cart.*; import com.company.platform.commerce.domain.pricing.Money; import com.company.platform.commerce.domain.events.CommerceEvent; import com.company.platform.commerce.infrastructure.*; import com.company.platform.commerce.application.PricingApplicationService; import org.springframework.web.bind.annotation.*; import java.util.*; import java.time.Instant;
@RestController @RequestMapping("/commerce") public class CartController { private final CartRepository carts; private final TenantContextProvider tenant;
 private final CartItemRepository items; private final PricingApplicationService pricing; private final KafkaCommerceEventPublisher events;
 public CartController(CartRepository carts,TenantContextProvider tenant,CartItemRepository items,PricingApplicationService pricing,KafkaCommerceEventPublisher events){this.carts=carts;this.tenant=tenant;this.items=items;this.pricing=pricing;this.events=events;} public record CreateCartRequest(UUID customerId,UUID storeId){} public record AddItemRequest(UUID productId,int quantity){} public record UpdateItemRequest(int quantity){}
 @PostMapping("/carts") public Cart create(@RequestBody CreateCartRequest r){var cart=Cart.create(tenant.currentTenantId(),r.customerId(),r.storeId());var saved=carts.save(cart);events.publish(new CommerceEvent(UUID.randomUUID(),"CartCreated",saved.id(),saved.tenantId(),Instant.now(),saved));return saved;}
 @GetMapping("/carts/{id}") public Cart get(@PathVariable UUID id){return carts.findByTenantIdAndId(tenant.currentTenantId(),id).orElseThrow();}
 @GetMapping("/customers/{id}/cart") public Cart customer(@PathVariable UUID id){return carts.findByTenantIdAndCustomerId(tenant.currentTenantId(),id).orElseThrow();}
 @PostMapping("/carts/{id}/items") public Cart add(@PathVariable UUID id,@RequestBody AddItemRequest r){var c=cart(id);var p=pricing.currentPrice(r.productId()).orElseThrow(()->new NoSuchElementException("active price not found"));c.addItem(new CartItem(null,c.id(),r.productId(),r.quantity(),p.money(),null,null));var saved=carts.save(c);events.publish(new CommerceEvent(UUID.randomUUID(),"ProductAddedToCart",saved.id(),saved.tenantId(),Instant.now(),r));return saved;}
 @PutMapping("/carts/{id}/items/{itemId}") public Cart update(@PathVariable UUID id,@PathVariable UUID itemId,@RequestBody UpdateItemRequest r){var c=cart(id);c.updateQuantity(itemId,r.quantity());return carts.save(c);}
 @DeleteMapping("/carts/{id}/items/{itemId}") public Cart remove(@PathVariable UUID id,@PathVariable UUID itemId){var c=cart(id);c.removeItem(itemId);items.deleteByTenantIdAndCartIdAndId(tenant.currentTenantId(),id,itemId);return carts.save(c);}
 private Cart cart(UUID id){return carts.findByTenantIdAndId(tenant.currentTenantId(),id).orElseThrow(()->new NoSuchElementException("cart not found"));}
}
