package com.company.platform.commerce.api;
import com.company.platform.commerce.application.*;import com.company.platform.commerce.domain.pricing.*;import com.company.platform.commerce.domain.product.*;import java.math.BigDecimal;import java.time.Instant;import java.util.*;import org.springframework.http.HttpStatus;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/products") public class ProductController { private final ProductApplicationService products;private final PricingApplicationService pricing;public ProductController(ProductApplicationService products,PricingApplicationService pricing){this.products=products;this.pricing=pricing;} public record CreateRequest(String sku,String name,String description){}public record UpdateRequest(String name,String description){}public record StatusRequest(ProductStatus status){}public record PriceRequest(BigDecimal amount,String currency,Instant validFrom,Instant validUntil){}
 @PostMapping @ResponseStatus(HttpStatus.CREATED) @PreAuthorize("hasAnyAuthority('PRODUCT_CREATE','TENANT_OWNER','TENANT_ADMIN','TENANT_MANAGER')")public Product create(@RequestBody CreateRequest r){return products.create(r.sku(),r.name(),r.description());}
 @GetMapping public List<Product> list(@RequestParam(required=false)String q,@RequestParam(required=false)ProductStatus status){return products.search(q,status);}@GetMapping("/{id}")public Product get(@PathVariable UUID id){return products.get(id);}
 @PutMapping("/{id}") @PreAuthorize("hasAnyAuthority('PRODUCT_UPDATE','TENANT_OWNER','TENANT_ADMIN','TENANT_MANAGER')")public Product update(@PathVariable UUID id,@RequestBody UpdateRequest r){return products.update(id,r.name(),r.description());}
 @PatchMapping("/{id}/status") @PreAuthorize("hasAnyAuthority('PRODUCT_UPDATE','TENANT_OWNER','TENANT_ADMIN','TENANT_MANAGER')")public Product status(@PathVariable UUID id,@RequestBody StatusRequest r){return products.changeStatus(id,r.status());}
 @PostMapping("/{id}/prices") @PreAuthorize("hasAnyAuthority('PRODUCT_UPDATE','TENANT_OWNER','TENANT_ADMIN','TENANT_MANAGER')")public Price price(@PathVariable UUID id,@RequestBody PriceRequest r){return pricing.createPrice(id,new Money(r.amount(),Currency.getInstance(r.currency())),r.validFrom(),r.validUntil());}
 @GetMapping("/{id}/prices")public List<Price> prices(@PathVariable UUID id){products.get(id);return pricing.prices(id);}
 @GetMapping("/{id}/price")public Price currentPrice(@PathVariable UUID id){return pricing.currentPrice(id).orElseThrow(()->new NoSuchElementException("PRICE_NOT_FOUND"));}
}
