package com.company.platform.commerce.api;
import com.company.platform.commerce.application.*;import com.company.platform.commerce.domain.pricing.*;import com.company.platform.commerce.domain.product.*;import java.math.BigDecimal;import java.time.Instant;import java.util.*;import org.springframework.http.HttpStatus;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/products") public class ProductController { private final ProductApplicationService products;private final PricingApplicationService pricing;public ProductController(ProductApplicationService products,PricingApplicationService pricing){this.products=products;this.pricing=pricing;} public record CreateRequest(String sku,String name,String description){}public record UpdateRequest(String name,String description){}public record StatusRequest(ProductStatus status){}public record PriceRequest(BigDecimal amount,String currency,Instant validFrom,Instant validUntil){}
 public record ProductResponse(UUID id,UUID tenantId,String sku,String name,String description,String status){static ProductResponse of(Product p){return new ProductResponse(p.id(),p.tenantId(),p.sku().value(),p.name().value(),p.description(),p.status().name());}}
 public record MoneyResponse(BigDecimal amount,String currency){static MoneyResponse of(Money m){return new MoneyResponse(m.amount(),m.currency().getCurrencyCode());}}
 public record PriceResponse(UUID id,UUID tenantId,UUID sellableProductId,MoneyResponse money,Instant validFrom,Instant validUntil,String status){static PriceResponse of(Price p){return new PriceResponse(p.id(),p.tenantId(),p.sellableProductId(),MoneyResponse.of(p.money()),p.validFrom(),p.validUntil(),p.status().name());}}
 @PostMapping @ResponseStatus(HttpStatus.CREATED) @PreAuthorize("hasAnyAuthority('PRODUCT_CREATE','TENANT_OWNER','TENANT_ADMIN','TENANT_MANAGER')")public ProductResponse create(@RequestBody CreateRequest r){return ProductResponse.of(products.create(r.sku(),r.name(),r.description()));}
 @GetMapping public List<ProductResponse> list(@RequestParam(required=false)String q,@RequestParam(required=false)ProductStatus status){return products.search(q,status).stream().map(ProductResponse::of).toList();}@GetMapping("/{id}")public ProductResponse get(@PathVariable UUID id){return ProductResponse.of(products.get(id));}
 @PutMapping("/{id}") @PreAuthorize("hasAnyAuthority('PRODUCT_UPDATE','TENANT_OWNER','TENANT_ADMIN','TENANT_MANAGER')")public ProductResponse update(@PathVariable UUID id,@RequestBody UpdateRequest r){return ProductResponse.of(products.update(id,r.name(),r.description()));}
 @PatchMapping("/{id}/status") @PreAuthorize("hasAnyAuthority('PRODUCT_UPDATE','TENANT_OWNER','TENANT_ADMIN','TENANT_MANAGER')")public ProductResponse status(@PathVariable UUID id,@RequestBody StatusRequest r){return ProductResponse.of(products.changeStatus(id,r.status()));}
 @PostMapping("/{id}/prices") @PreAuthorize("hasAnyAuthority('PRODUCT_UPDATE','TENANT_OWNER','TENANT_ADMIN','TENANT_MANAGER')")public PriceResponse price(@PathVariable UUID id,@RequestBody PriceRequest r){return PriceResponse.of(pricing.createPrice(id,new Money(r.amount(),Currency.getInstance(r.currency())),r.validFrom(),r.validUntil()));}
 @GetMapping("/{id}/prices")public List<PriceResponse> prices(@PathVariable UUID id){products.get(id);return pricing.prices(id).stream().map(PriceResponse::of).toList();}
 @GetMapping("/{id}/price")public PriceResponse currentPrice(@PathVariable UUID id){return PriceResponse.of(pricing.currentPrice(id).orElseThrow(()->new NoSuchElementException("PRICE_NOT_FOUND")));}
}
