package com.company.platform.analytics.application;
import com.company.platform.analytics.infrastructure.TenantContextProvider;import java.time.*;import java.util.*;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.stereotype.Service;
@Service public class AnalyticsQueryService {private final JdbcTemplate jdbc;private final TenantContextProvider tenant;public AnalyticsQueryService(JdbcTemplate j,TenantContextProvider t){jdbc=j;tenant=t;}private UUID t(){return tenant.currentTenantId();}private Range range(String from,String to){try{LocalDate f=from==null?LocalDate.of(1970,1,1):LocalDate.parse(from);LocalDate end=to==null?LocalDate.now(ZoneOffset.UTC).plusDays(1):LocalDate.parse(to).plusDays(1);if(f.isAfter(end.minusDays(1)))throw new IllegalArgumentException("INVALID_DATE_RANGE");return new Range(f.atStartOfDay(ZoneOffset.UTC).toInstant(),end.atStartOfDay(ZoneOffset.UTC).toInstant());}catch(DateTimeException e){throw new IllegalArgumentException("INVALID_DATE_RANGE",e);}}private record Range(Instant from,Instant to){}private List<Map<String,Object>> q(String sql,String from,String to,Object...extra){Range r=range(from,to);List<Object> args=new ArrayList<>();args.add(t());args.add(r.from());args.add(r.to());args.addAll(List.of(extra));return jdbc.queryForList(sql,t(),r.from(),r.to(),extra);}
 public Map<String,Object> overview(String from,String to){Range r=range(from,to);return jdbc.queryForMap("SELECT COUNT(*) FILTER(WHERE event_type='ORDER_CREATED') orders_created,COUNT(*) FILTER(WHERE event_type='ORDER_CONFIRMED') orders_confirmed,COUNT(*) FILTER(WHERE event_type='ORDER_CANCELLED') orders_cancelled,COALESCE(SUM(amount) FILTER(WHERE event_type='ORDER_CONFIRMED'),0) total_sales,COALESCE(SUM(amount) FILTER(WHERE event_type='PAYMENT_PAID'),0) paid_amount,COUNT(*) FILTER(WHERE event_type='PAYMENT_FAILED') failed_payments,COALESCE(SUM(quantity) FILTER(WHERE event_type LIKE 'INVENTORY_%'),0) inventory_quantity FROM analytics_metrics WHERE tenant_id=? AND occurred_at>=? AND occurred_at<?",t(),r.from(),r.to());}
 public List<Map<String,Object>> sales(String from,String to){Range r=range(from,to);return jdbc.queryForList("SELECT DATE(occurred_at AT TIME ZONE 'UTC') day,COUNT(*) FILTER(WHERE event_type='ORDER_CONFIRMED') orders,COALESCE(SUM(amount) FILTER(WHERE event_type='ORDER_CONFIRMED'),0) gross_sales,COALESCE(SUM(amount) FILTER(WHERE event_type='PAYMENT_PAID'),0) paid_sales FROM analytics_metrics WHERE tenant_id=? AND occurred_at>=? AND occurred_at<? GROUP BY 1 ORDER BY 1 DESC",t(),r.from(),r.to());}
 public List<Map<String,Object>> orders(String from,String to){Range r=range(from,to);return jdbc.queryForList("SELECT event_type,COUNT(*) count,COALESCE(SUM(amount),0) amount FROM analytics_metrics WHERE tenant_id=? AND occurred_at>=? AND occurred_at<? AND event_type LIKE 'ORDER_%' GROUP BY event_type ORDER BY event_type",t(),r.from(),r.to());}
 public List<Map<String,Object>> payments(String from,String to){Range r=range(from,to);return jdbc.queryForList("SELECT event_type,COUNT(*) count,COALESCE(SUM(amount),0) amount FROM analytics_metrics WHERE tenant_id=? AND occurred_at>=? AND occurred_at<? AND event_type LIKE 'PAYMENT_%' GROUP BY event_type ORDER BY event_type",t(),r.from(),r.to());}
 public List<Map<String,Object>> inventory(String from,String to){Range r=range(from,to);return jdbc.queryForList("SELECT event_type,COUNT(*) count,COALESCE(SUM(quantity),0) quantity FROM analytics_metrics WHERE tenant_id=? AND occurred_at>=? AND occurred_at<? AND event_type LIKE 'INVENTORY_%' GROUP BY event_type ORDER BY event_type",t(),r.from(),r.to());}
 public List<Map<String,Object>> products(String from,String to){Range r=range(from,to);return jdbc.queryForList("SELECT product_id,COUNT(*) events,COALESCE(SUM(quantity),0) quantity,COALESCE(SUM(amount),0) amount FROM analytics_metrics WHERE tenant_id=? AND product_id IS NOT NULL AND occurred_at>=? AND occurred_at<? GROUP BY product_id ORDER BY quantity DESC LIMIT 100",t(),r.from(),r.to());}
 public List<Map<String,Object>> dashboard(){return sales(null,null);} }
