package com.company.platform.payment.application;

import com.company.platform.payment.domain.*;
import com.company.platform.payment.infrastructure.TenantContextProvider;
import com.company.platform.payment.infrastructure.PaymentEventPublisher;
import java.math.BigDecimal; import java.nio.charset.StandardCharsets; import java.security.MessageDigest; import java.time.Instant; import java.util.*;
import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;

@Service
public class PaymentApplicationService {
    private final PaymentRepository payments; private final PaymentAttemptRepository attempts; private final InvoiceRepository invoices; private final RefundRepository refunds; private final IdempotencyRepository idempotency; private final PaymentGateway gateway; private final TenantContextProvider tenant; private final PaymentEventPublisher events;
    public PaymentApplicationService(PaymentRepository payments,PaymentAttemptRepository attempts,InvoiceRepository invoices,RefundRepository refunds,IdempotencyRepository idempotency,PaymentGateway gateway,TenantContextProvider tenant,PaymentEventPublisher events){this.payments=payments;this.attempts=attempts;this.invoices=invoices;this.refunds=refunds;this.idempotency=idempotency;this.gateway=gateway;this.tenant=tenant;this.events=events;}
    public UUID tenantId(){return tenant.currentTenantId();}
    @Transactional public Payment create(UUID orderId,UUID customerId,String reference,Currency currency,BigDecimal amount,PaymentMethod method,String key){UUID t=tenantId();String input=reference+orderId+amount;Optional<IdempotencyRepository.IdempotencyRecord> previous=existing(t,"CREATE",key,input);if(previous.isPresent())return payments.findByTenantIdAndReference(t,reference).orElseThrow(()->new IllegalStateException("idempotency result not found"));return idempotent(t,"CREATE",key,input,()->{Payment p=payments.save(Payment.create(t,orderId,customerId,reference,currency,amount,method));events.publish("PaymentCreatedEvent",t,p.id(),p);return p;});}
    @Transactional public Payment authorize(UUID id){Payment p=payment(id);if(p.status()==PaymentStatus.CREATED||p.status()==PaymentStatus.FAILED||p.status()==PaymentStatus.DECLINED)p.pending();PaymentGateway.GatewayResult result=gateway.authorize(p);PaymentAttempt a=new PaymentAttempt(UUID.randomUUID(),p.tenantId(),p.id(),result.provider(),attempts.nextAttemptNumber(p.tenantId(),p.id()),result.successful()?AttemptStatus.AUTHORIZED:AttemptStatus.FAILED,result.providerReference(),Instant.now(),Instant.now(),result.failureReason());attempts.save(a);if(result.successful()){p.authorize();events.publish("PaymentAuthorizedEvent",p.tenantId(),p.id(),p);}else{p.fail();events.publish("PaymentFailedEvent",p.tenantId(),p.id(),p);}return payments.save(p);}
    @Transactional public Payment capture(UUID id){Payment p=payment(id);PaymentGateway.GatewayResult result=gateway.capture(p);if(!result.successful())throw new IllegalStateException(result.failureReason());p.capture();attempts.save(new PaymentAttempt(UUID.randomUUID(),p.tenantId(),p.id(),result.provider(),attempts.nextAttemptNumber(p.tenantId(),p.id()),AttemptStatus.CAPTURED,result.providerReference(),Instant.now(),Instant.now(),null));Payment saved=payments.save(p);events.publish("PaymentCapturedEvent",p.tenantId(),p.id(),p);return saved;}
    @Transactional public Payment cancel(UUID id){Payment p=payment(id);PaymentGateway.GatewayResult result=gateway.cancel(p);if(!result.successful())throw new IllegalStateException(result.failureReason());p.cancel();Payment saved=payments.save(p);events.publish("PaymentCancelledEvent",p.tenantId(),p.id(),p);return saved;}
    @Transactional public Payment retry(UUID id){Payment p=payment(id);if(p.status()!=PaymentStatus.FAILED&&p.status()!=PaymentStatus.DECLINED)throw new IllegalStateException("payment is not retryable");p.pending();return authorize(id);}
    public Payment get(UUID id){return payment(id);} public List<Payment> byOrder(UUID orderId){return payments.findByTenantIdAndOrderId(tenantId(),orderId);}
    public List<Payment> list(){return payments.findByTenantId(tenantId());} public List<Payment> byCustomer(UUID customerId){return payments.findByTenantIdAndCustomerId(tenantId(),customerId);}
    @Transactional public Payment processOrderConfirmed(UUID confirmedTenant,UUID orderId,UUID customerId,BigDecimal amount,Currency currency,String eventId){if(confirmedTenant==null||orderId==null||amount==null||amount.signum()<=0||currency==null||eventId==null||eventId.isBlank())throw new IllegalArgumentException("INVALID_PAYMENT");var existing=payments.findByTenantIdAndOrderId(confirmedTenant,orderId);if(!existing.isEmpty())return existing.get(0);Payment p=payments.save(Payment.create(confirmedTenant,orderId,customerId,"order-"+orderId,currency,amount,PaymentMethod.CREDIT_CARD));p.pending();p.processing();events.publish("PAYMENT_CREATED",confirmedTenant,p.id(),Map.of("paymentId",p.id().toString(),"orderId",orderId.toString(),"amount",amount,"currency",currency.getCurrencyCode()));var result=gateway.authorize(p);if(!result.successful()){p.fail();payments.save(p);events.publish("PAYMENT_FAILED",confirmedTenant,p.id(),Map.of("paymentId",p.id().toString(),"orderId",orderId.toString(),"failureCode",result.failureReason()));return p;}p.authorize();p.paid();Payment saved=payments.save(p);events.publish("PAYMENT_PAID",confirmedTenant,p.id(),Map.of("paymentId",p.id().toString(),"orderId",orderId.toString(),"customerId",String.valueOf(customerId),"amount",amount,"currency",currency.getCurrencyCode(),"providerReference",result.providerReference()));return saved;}
    @Transactional public Refund createRefund(UUID paymentId,UUID orderId,String reference,BigDecimal amount,Currency currency,String reason,String key){UUID t=tenantId();String input=reference+paymentId+amount;Optional<IdempotencyRepository.IdempotencyRecord> previous=existing(t,"REFUND",key,input);if(previous.isPresent())return refunds.findByTenantIdAndReference(t,reference).orElseThrow(()->new IllegalStateException("idempotency result not found"));Payment p=payment(paymentId);if(!p.currency().equals(currency))throw new IllegalArgumentException("refund currency mismatch");BigDecimal used=refunds.findByTenantIdAndPaymentId(t,paymentId).stream().filter(r->r.status()==RefundStatus.PROCESSED||r.status()==RefundStatus.APPROVED||r.status()==RefundStatus.REQUESTED).map(Refund::amount).reduce(BigDecimal.ZERO,BigDecimal::add);if(used.add(amount).compareTo(p.amount())>0)throw new IllegalArgumentException("refund exceeds captured amount");return idempotent(t,"REFUND",key,input,()->refunds.save(Refund.create(t,paymentId,orderId,reference,amount,currency,reason)));}
    @Transactional public Refund approveRefund(UUID id){Refund r=refund(id);r.approve();return refunds.save(r);} @Transactional public Refund rejectRefund(UUID id){Refund r=refund(id);r.reject();return refunds.save(r);}
    @Transactional public Refund processRefund(UUID id){Refund r=refund(id);Payment p=payment(r.paymentId());PaymentGateway.GatewayResult result=gateway.refund(r);if(!result.successful()){r.fail();refunds.save(r);events.publish("RefundFailedEvent",r.tenantId(),r.id(),r);throw new IllegalStateException(result.failureReason());}r.process(result.providerReference());p.refunded(r.amount().compareTo(p.amount())<0);payments.save(p);Refund saved=refunds.save(r);events.publish("RefundProcessedEvent",r.tenantId(),r.id(),r);return saved;}
    public Invoice generateInvoice(UUID paymentId,String number){Payment p=payment(paymentId);if(p.status()!=PaymentStatus.CAPTURED&&p.status()!=PaymentStatus.SETTLED)throw new IllegalStateException("payment is not billable");if(invoices.findByTenantIdAndPaymentId(p.tenantId(),p.id()).isPresent())return invoices.findByTenantIdAndPaymentId(p.tenantId(),p.id()).orElseThrow();Invoice i=Invoice.create(p.tenantId(),number,p.id(),p.orderId(),p.customerId(),p.currency(),p.amount(),p.amount());i.pending();i.issue();return invoices.save(i);}
    public Invoice getInvoice(UUID id){return invoices.findByTenantIdAndId(tenantId(),id).orElseThrow(()->new NoSuchElementException("invoice not found"));} public List<Invoice> invoicesByOrder(UUID orderId){return invoices.findByTenantIdAndOrderId(tenantId(),orderId);} public Refund getRefund(UUID id){return refund(id);}
    private Payment payment(UUID id){return payments.findByTenantIdAndId(tenantId(),id).orElseThrow(()->new NoSuchElementException("payment not found"));} private Refund refund(UUID id){return refunds.findByTenantIdAndId(tenantId(),id).orElseThrow(()->new NoSuchElementException("refund not found"));}
    private <T> T idempotent(UUID tenantId,String operation,String key,String input,java.util.function.Supplier<T> action){if(key==null||key.isBlank())throw new IllegalArgumentException("Idempotency-Key is required");String hash=hash(input);Optional<IdempotencyRepository.IdempotencyRecord> existing=idempotency.find(tenantId,operation,key,Instant.now());if(existing.isPresent()){if(!existing.get().requestHash().equals(hash))throw new IllegalStateException("idempotency key payload conflict");return action.get();}T value=action.get();idempotency.save(new IdempotencyRepository.IdempotencyRecord(UUID.randomUUID(),tenantId,operation,key,hash,200,value.toString(),Instant.now(),Instant.now().plusSeconds(86400)));return value;}
    private Optional<IdempotencyRepository.IdempotencyRecord> existing(UUID tenantId,String operation,String key,String input){if(key==null||key.isBlank())throw new IllegalArgumentException("Idempotency-Key is required");Optional<IdempotencyRepository.IdempotencyRecord> value=idempotency.find(tenantId,operation,key,Instant.now());if(value.isPresent()&&!value.get().requestHash().equals(hash(input)))throw new IllegalStateException("idempotency key payload conflict");return value;}
    private String hash(String input){try{byte[] bytes=MessageDigest.getInstance("SHA-256").digest(input.getBytes(StandardCharsets.UTF_8));return HexFormat.of().formatHex(bytes);}catch(Exception e){throw new IllegalStateException(e);}}
}
