package com.company.platform.order.domain;

import java.time.Instant;
import java.util.*;

public final class Order {
 private final UUID id,tenantId,customerId,storeId; private final OrderNumber orderNumber; private final List<OrderItem> items=new ArrayList<>(); private OrderStatus status; private final Currency currency; private Money subtotal; private final Instant createdAt; private Instant updatedAt;
 private Order(UUID id,UUID tenantId,OrderNumber number,UUID customerId,UUID storeId,OrderStatus status,Currency currency,Money subtotal,Instant createdAt,Instant updatedAt,List<OrderItem> lines){if(tenantId==null||number==null||customerId==null||storeId==null||currency==null)throw new IllegalArgumentException("order ownership required");this.id=id==null?UUID.randomUUID():id;this.tenantId=tenantId;this.orderNumber=number;this.customerId=customerId;this.storeId=storeId;this.status=status==null?OrderStatus.DRAFT:status;this.currency=currency;this.subtotal=subtotal==null?Money.zero(currency):subtotal;this.createdAt=createdAt==null?Instant.now():createdAt;this.updatedAt=updatedAt==null?this.createdAt:updatedAt;if(lines!=null)this.items.addAll(lines);}
 public static Order create(UUID tenantId,OrderNumber number,UUID customerId,UUID storeId,Currency currency){return new Order(null,tenantId,number,customerId,storeId,null,currency,null,null,null,null);}
 public static Order rehydrate(UUID id,UUID tenantId,OrderNumber number,UUID customerId,UUID storeId,OrderStatus status,Currency currency,Money subtotal,Instant createdAt,Instant updatedAt,List<OrderItem> lines){return new Order(id,tenantId,number,customerId,storeId,status,currency,subtotal,createdAt,updatedAt,lines);}
 public void addItem(OrderItem item){if(!status.editable())throw new IllegalStateException("ORDER_NOT_EDITABLE");if(!item.orderId().equals(id)||!item.unitPrice().currency().equals(currency))throw new IllegalArgumentException("currency mismatch");items.add(item);recalculate();}
 public void updateItem(UUID lineId,int quantity){if(!status.editable())throw new IllegalStateException("ORDER_NOT_EDITABLE");for(int i=0;i<items.size();i++)if(items.get(i).id().equals(lineId)){items.set(i,items.get(i).withQuantity(quantity));recalculate();return;}throw new NoSuchElementException("ORDER_LINE_NOT_FOUND");}
 public void removeItem(UUID lineId){if(!status.editable())throw new IllegalStateException("ORDER_NOT_EDITABLE");if(!items.removeIf(x->x.id().equals(lineId)))throw new NoSuchElementException("ORDER_LINE_NOT_FOUND");recalculate();}
 public void submit(){if(items.isEmpty())throw new IllegalStateException("ORDER_EMPTY");transition(OrderStatus.PENDING);}
 public void confirm(){if(status!=OrderStatus.PENDING&&status!=OrderStatus.PENDING_CONFIRMATION)throw new IllegalStateException("ORDER_INVALID_TRANSITION");transition(OrderStatus.CONFIRMED);}
 public void cancel(){if(status.terminal()||status==OrderStatus.PROCESSING)throw new IllegalStateException("ORDER_INVALID_TRANSITION");transition(OrderStatus.CANCELLED);}
 public void expire(){if(status!=OrderStatus.PENDING&&status!=OrderStatus.PENDING_CONFIRMATION)throw new IllegalStateException("ORDER_INVALID_TRANSITION");transition(OrderStatus.EXPIRED);}
 public void startProcessing(){if(status!=OrderStatus.CONFIRMED)throw new IllegalStateException("ORDER_INVALID_TRANSITION");transition(OrderStatus.PROCESSING);} public void complete(){if(status!=OrderStatus.PROCESSING)throw new IllegalStateException("ORDER_INVALID_TRANSITION");transition(OrderStatus.COMPLETED);}
 private void transition(OrderStatus next){status=next;updatedAt=Instant.now();} private void recalculate(){subtotal=items.stream().map(OrderItem::subtotal).reduce(Money.zero(currency),Money::add);updatedAt=Instant.now();}
 public UUID id(){return id;}public UUID tenantId(){return tenantId;}public OrderNumber orderNumber(){return orderNumber;}public UUID customerId(){return customerId;}public UUID storeId(){return storeId;}public OrderStatus status(){return status;}public Currency currency(){return currency;}public Money subtotal(){return subtotal;}public Money total(){return subtotal;}public List<OrderItem> items(){return List.copyOf(items);}public Instant createdAt(){return createdAt;}public Instant updatedAt(){return updatedAt;}
}
