package com.company.platform.commerce.domain.cart;
import java.time.Instant; import java.util.*;
public final class Cart {
 private final UUID id,tenantId,customerId,storeId; private final List<CartItem> items=new ArrayList<>(); private CartStatus status; private final Instant createdAt; private Instant updatedAt;
 private Cart(UUID id,UUID tenantId,UUID customerId,UUID storeId,CartStatus status,Instant createdAt,Instant updatedAt,List<CartItem> items){if(tenantId==null||customerId==null||storeId==null)throw new IllegalArgumentException("cart ownership required");this.id=id==null?UUID.randomUUID():id;this.tenantId=tenantId;this.customerId=customerId;this.storeId=storeId;this.status=status==null?CartStatus.ACTIVE:status;this.createdAt=createdAt==null?Instant.now():createdAt;this.updatedAt=updatedAt==null?this.createdAt:updatedAt;if(items!=null)this.items.addAll(items);}
 private Cart(UUID tenantId,UUID customerId,UUID storeId){this(null,tenantId,customerId,storeId,null,null,null,null);}
 public static Cart create(UUID tenantId,UUID customerId,UUID storeId){return new Cart(tenantId,customerId,storeId);} public void addItem(CartItem item){ensureActive();if(!item.cartId().equals(id))throw new IllegalArgumentException("item belongs to another cart");items.removeIf(i->i.sellableProductId().equals(item.sellableProductId()));items.add(item);touch();} public void removeItem(UUID itemId){ensureActive();items.removeIf(i->i.id().equals(itemId));touch();} public void complete(){status=CartStatus.COMPLETED;touch();} private void ensureActive(){if(status!=CartStatus.ACTIVE)throw new IllegalStateException("cart is not active");} private void touch(){updatedAt=Instant.now();}
 public static Cart rehydrate(UUID id,UUID tenantId,UUID customerId,UUID storeId,CartStatus status,Instant createdAt,Instant updatedAt,List<CartItem> items){return new Cart(id,tenantId,customerId,storeId,status,createdAt,updatedAt,items);} public void updateQuantity(UUID itemId,int quantity){ensureActive();if(quantity<=0)throw new IllegalArgumentException("quantity must be positive");for(var i=0;i<items.size();i++){var old=items.get(i);if(old.id().equals(itemId)){items.set(i,new CartItem(old.id(),old.cartId(),old.sellableProductId(),quantity,old.unitPrice(),old.createdAt(),Instant.now()));touch();return;}}throw new NoSuchElementException("cart item not found");}
 public UUID id(){return id;} public UUID tenantId(){return tenantId;} public UUID customerId(){return customerId;} public UUID storeId(){return storeId;} public CartStatus status(){return status;} public List<CartItem> items(){return List.copyOf(items);} public Instant createdAt(){return createdAt;} public Instant updatedAt(){return updatedAt;}
}
