package com.company.platform.inventory.api;
import com.company.platform.inventory.application.*;import com.company.platform.inventory.domain.Inventory;import java.math.BigDecimal;import java.util.*;import org.springframework.http.*;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api") public class InventoryController {private final InventoryService service;public InventoryController(InventoryService s){service=s;}public record CreateRequest(UUID productId,UUID warehouseLocationId){}public record QuantityRequest(BigDecimal quantity){}public record ReserveRequest(UUID orderId,BigDecimal quantity,String reference){}
 @PostMapping("/inventory") @ResponseStatus(HttpStatus.CREATED) @PreAuthorize("hasAnyAuthority('INVENTORY_WRITE','TENANT_OWNER','TENANT_ADMIN','TENANT_MANAGER')") public Inventory create(@RequestBody CreateRequest r){return service.create(r.productId(),r.warehouseLocationId());}
 @GetMapping("/inventory") @PreAuthorize("hasAnyAuthority('INVENTORY_READ','TENANT_OWNER','TENANT_ADMIN','TENANT_MANAGER')") public List<Inventory> list(){return service.list();}@GetMapping("/inventory/{productId}") @PreAuthorize("hasAnyAuthority('INVENTORY_READ','TENANT_OWNER','TENANT_ADMIN','TENANT_MANAGER')") public List<Inventory> byProduct(@PathVariable UUID productId){return service.byProduct(productId);}
 @PostMapping("/inventory/{productId}/stock") @PreAuthorize("hasAnyAuthority('INVENTORY_WRITE','TENANT_OWNER','TENANT_ADMIN','TENANT_MANAGER')") public Inventory stock(@PathVariable UUID productId,@RequestBody QuantityRequest r){var i=service.byProduct(productId).stream().findFirst().orElseThrow(()->new NoSuchElementException("INVENTORY_NOT_FOUND"));return service.adjust(i.id(),r.quantity());}
 @PostMapping("/inventory/{productId}/reserve") @ResponseStatus(HttpStatus.CREATED) @PreAuthorize("hasAnyAuthority('INVENTORY_RESERVE','ORDER_CREATE','TENANT_OWNER','TENANT_ADMIN','TENANT_MANAGER')") public ReservationStore.ReservationRecord reserve(@PathVariable UUID productId,@RequestBody ReserveRequest r){return service.reserveProduct(productId,r.orderId(),r.quantity(),r.reference());}
 @PostMapping("/reservations/{id}/release") @PreAuthorize("hasAnyAuthority('INVENTORY_UPDATE','TENANT_OWNER','TENANT_ADMIN','TENANT_MANAGER')") public ReservationStore.ReservationRecord release(@PathVariable UUID id){return service.releaseReservation(id);}@PostMapping("/reservations/{id}/consume") @PreAuthorize("hasAnyAuthority('INVENTORY_UPDATE','TENANT_OWNER','TENANT_ADMIN','TENANT_MANAGER')") public ReservationStore.ReservationRecord consume(@PathVariable UUID id){return service.consumeReservation(id);}
 @ExceptionHandler(NoSuchElementException.class) ResponseEntity<Map<String,String>> notFound(Exception e){return ResponseEntity.status(404).body(Map.of("error",e.getMessage()));}@ExceptionHandler({IllegalArgumentException.class,IllegalStateException.class}) ResponseEntity<Map<String,String>> invalid(Exception e){return ResponseEntity.status(422).body(Map.of("error",e.getMessage()));}
}
