package com.company.platform.payment.api;
import com.company.platform.payment.application.PaymentApplicationService;import com.company.platform.payment.domain.*;import java.math.BigDecimal;import java.util.*;import org.springframework.http.HttpStatus;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api") public class PaymentController {private final PaymentApplicationService service;public PaymentController(PaymentApplicationService service){this.service=service;}public record CreatePaymentRequest(UUID orderId,UUID customerId,String paymentReference,String currency,BigDecimal amount,PaymentMethod paymentMethod){}public record CreateInvoiceRequest(UUID paymentId,String invoiceNumber){}public record CreateRefundRequest(UUID paymentId,UUID orderId,String refundReference,BigDecimal amount,String currency,String reason){}
 @PostMapping("/payments") @PreAuthorize("hasAnyAuthority('PAYMENT_CREATE','TENANT_OWNER','TENANT_ADMIN','TENANT_MANAGER')") public Payment create(@RequestHeader("Idempotency-Key")String key,@RequestBody CreatePaymentRequest r){return service.create(r.orderId(),r.customerId(),r.paymentReference(),Currency.getInstance(r.currency()),r.amount(),r.paymentMethod(),key);}
 @GetMapping("/payments") @PreAuthorize("hasAnyAuthority('PAYMENT_READ','TENANT_OWNER','TENANT_ADMIN','TENANT_MANAGER')") public List<Payment> list(){return service.list();}
 @GetMapping("/payments/{id}") @PreAuthorize("hasAnyAuthority('PAYMENT_READ','TENANT_OWNER','TENANT_ADMIN','TENANT_MANAGER')") public Payment get(@PathVariable UUID id){return service.get(id);}
 @GetMapping("/payments/order/{orderId}") @PreAuthorize("hasAnyAuthority('PAYMENT_READ','TENANT_OWNER','TENANT_ADMIN','TENANT_MANAGER')") public List<Payment> byOrder(@PathVariable UUID orderId){return service.byOrder(orderId);}
 @PostMapping("/payments/{id}/authorize") @PreAuthorize("hasAnyAuthority('PAYMENT_UPDATE','TENANT_OWNER','TENANT_ADMIN','TENANT_MANAGER')") public Payment authorize(@PathVariable UUID id){return service.authorize(id);}@PostMapping("/payments/{id}/capture") @PreAuthorize("hasAnyAuthority('PAYMENT_UPDATE','TENANT_OWNER','TENANT_ADMIN','TENANT_MANAGER')") public Payment capture(@PathVariable UUID id){return service.capture(id);}@PostMapping("/payments/{id}/cancel") @PreAuthorize("hasAnyAuthority('PAYMENT_CANCEL','PAYMENT_UPDATE','TENANT_OWNER','TENANT_ADMIN','TENANT_MANAGER')") public Payment cancel(@PathVariable UUID id){return service.cancel(id);}
 @PostMapping("/payments/{id}/retry") @PreAuthorize("hasAnyAuthority('PAYMENT_UPDATE','TENANT_OWNER','TENANT_ADMIN','TENANT_MANAGER')") public Payment retry(@PathVariable UUID id){return service.retry(id);}
 @PostMapping("/billing/invoices") @PreAuthorize("hasAnyAuthority('PAYMENT_CREATE','TENANT_OWNER','TENANT_ADMIN','TENANT_MANAGER')") public Invoice invoice(@RequestHeader("Idempotency-Key")String key,@RequestBody CreateInvoiceRequest r){return service.generateInvoice(r.paymentId(),r.invoiceNumber());}@GetMapping("/billing/invoices/{id}") public Invoice getInvoice(@PathVariable UUID id){return service.getInvoice(id);}@GetMapping("/billing/invoices/order/{orderId}") public List<Invoice> invoicesByOrder(@PathVariable UUID orderId){return service.invoicesByOrder(orderId);}
 @PostMapping("/billing/refunds") @PreAuthorize("hasAnyAuthority('PAYMENT_UPDATE','TENANT_OWNER','TENANT_ADMIN','TENANT_MANAGER')") public Refund refund(@RequestHeader("Idempotency-Key")String key,@RequestBody CreateRefundRequest r){return service.createRefund(r.paymentId(),r.orderId(),r.refundReference(),r.amount(),Currency.getInstance(r.currency()),r.reason(),key);}@GetMapping("/billing/refunds/{id}") public Refund getRefund(@PathVariable UUID id){return service.getRefund(id);}@PostMapping("/billing/refunds/{id}/approve") public Refund approve(@PathVariable UUID id){return service.approveRefund(id);}@PostMapping("/billing/refunds/{id}/reject") public Refund reject(@PathVariable UUID id){return service.rejectRefund(id);}@PostMapping("/billing/refunds/{id}/process") public Refund process(@PathVariable UUID id){return service.processRefund(id);}
 @ExceptionHandler(NoSuchElementException.class) @ResponseStatus(HttpStatus.NOT_FOUND) public Map<String,String> notFound(Exception e){return Map.of("error",e.getMessage());}@ExceptionHandler({IllegalArgumentException.class,IllegalStateException.class}) @ResponseStatus(HttpStatus.UNPROCESSABLE_ENTITY) public Map<String,String> invalid(Exception e){return Map.of("error",e.getMessage());}
}
