package com.company.platform.payment.domain;

import java.math.BigDecimal; import java.time.Instant; import java.util.Currency; import java.util.UUID;

public final class Refund {
    private final UUID id,tenantId,paymentId,orderId; private final String reference,reason; private final BigDecimal amount; private final Currency currency;
    private RefundStatus status; private final Instant createdAt; private Instant updatedAt,processedAt; private String providerReference;
    private Refund(UUID id,UUID tenantId,UUID paymentId,UUID orderId,String reference,BigDecimal amount,Currency currency,String reason,RefundStatus status,String providerReference,Instant createdAt,Instant updatedAt,Instant processedAt){if(tenantId==null||paymentId==null||orderId==null||reference==null||reference.isBlank()||currency==null||reason==null||reason.isBlank()||amount==null||amount.signum()<=0)throw new IllegalArgumentException("invalid refund");this.id=id==null?UUID.randomUUID():id;this.tenantId=tenantId;this.paymentId=paymentId;this.orderId=orderId;this.reference=reference;this.amount=amount;this.currency=currency;this.reason=reason;this.status=status==null?RefundStatus.REQUESTED:status;this.providerReference=providerReference;this.createdAt=createdAt==null?Instant.now():createdAt;this.updatedAt=updatedAt==null?this.createdAt:updatedAt;this.processedAt=processedAt;}
    public static Refund create(UUID tenantId,UUID paymentId,UUID orderId,String reference,BigDecimal amount,Currency currency,String reason){return new Refund(null,tenantId,paymentId,orderId,reference,amount,currency,reason,null,null,null,null,null);}
    public static Refund rehydrate(UUID id,UUID tenantId,UUID paymentId,UUID orderId,String reference,BigDecimal amount,Currency currency,String reason,RefundStatus status,String providerReference,Instant createdAt,Instant updatedAt,Instant processedAt){return new Refund(id,tenantId,paymentId,orderId,reference,amount,currency,reason,status,providerReference,createdAt,updatedAt,processedAt);}
    public void approve(){if(status!=RefundStatus.REQUESTED)throw new IllegalStateException("invalid refund approval");status=RefundStatus.APPROVED;touch();} public void reject(){if(status!=RefundStatus.REQUESTED)throw new IllegalStateException("invalid refund rejection");status=RefundStatus.REJECTED;touch();} public void cancel(){if(status!=RefundStatus.REQUESTED&&status!=RefundStatus.APPROVED)throw new IllegalStateException("invalid refund cancellation");status=RefundStatus.CANCELLED;touch();} public void process(String providerReference){if(status!=RefundStatus.APPROVED)throw new IllegalStateException("refund requires approval");status=RefundStatus.PROCESSED;this.providerReference=providerReference;processedAt=Instant.now();touch();} public void fail(){if(status!=RefundStatus.APPROVED)throw new IllegalStateException("invalid refund failure");status=RefundStatus.FAILED;touch();} private void touch(){updatedAt=Instant.now();}
    public UUID id(){return id;} public UUID tenantId(){return tenantId;} public UUID paymentId(){return paymentId;} public UUID orderId(){return orderId;} public String reference(){return reference;} public BigDecimal amount(){return amount;} public Currency currency(){return currency;} public String reason(){return reason;} public RefundStatus status(){return status;} public String providerReference(){return providerReference;} public Instant createdAt(){return createdAt;} public Instant updatedAt(){return updatedAt;} public Instant processedAt(){return processedAt;}
}
