ALTER TABLE warehouses ADD COLUMN IF NOT EXISTS description VARCHAR(512) NOT NULL DEFAULT '';
ALTER TABLE warehouses ADD COLUMN IF NOT EXISTS status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE';
ALTER TABLE inventory ADD COLUMN IF NOT EXISTS damaged NUMERIC(19,4) NOT NULL DEFAULT 0 CHECK(damaged>=0);
ALTER TABLE inventory ADD COLUMN IF NOT EXISTS minimum_stock NUMERIC(19,4) NOT NULL DEFAULT 0 CHECK(minimum_stock>=0);
ALTER TABLE inventory ADD COLUMN IF NOT EXISTS maximum_stock NUMERIC(19,4) NOT NULL DEFAULT 0 CHECK(maximum_stock>=0);
