package com.company.platform.commerce.domain.pricing;
import java.time.*; import java.util.UUID;
public final class Price {
 private final UUID id,tenantId,sellableProductId; private final Money money; private final Instant validFrom,validUntil,createdAt; private Instant updatedAt; private PriceStatus status;
 private Price(UUID id,UUID tenantId,UUID sellableProductId,Money money,Instant validFrom,Instant validUntil,PriceStatus status,Instant createdAt,Instant updatedAt){if(tenantId==null||sellableProductId==null||money==null||validFrom==null||validUntil==null||!validUntil.isAfter(validFrom))throw new IllegalArgumentException("invalid price");this.id=id==null?UUID.randomUUID():id;this.tenantId=tenantId;this.sellableProductId=sellableProductId;this.money=money;this.validFrom=validFrom;this.validUntil=validUntil;this.status=status==null?PriceStatus.DRAFT:status;this.createdAt=createdAt==null?Instant.now():createdAt;this.updatedAt=updatedAt==null?this.createdAt:updatedAt;}
 private Price(UUID tenantId,UUID sellableProductId,Money money,Instant validFrom,Instant validUntil){this(null,tenantId,sellableProductId,money,validFrom,validUntil,null,null,null);}
 public static Price create(UUID tenantId,UUID productId,Money money,Instant from,Instant until){return new Price(tenantId,productId,money,from,until);} public void activate(){if(status!=PriceStatus.DRAFT)throw new IllegalStateException("only draft price can activate");status=PriceStatus.ACTIVE;touch();} public void expire(){if(status!=PriceStatus.ACTIVE)throw new IllegalStateException("only active price can expire");status=PriceStatus.EXPIRED;touch();} private void touch(){updatedAt=Instant.now();}
 public static Price rehydrate(UUID id,UUID tenantId,UUID productId,Money money,Instant from,Instant until,PriceStatus status,Instant createdAt,Instant updatedAt){return new Price(id,tenantId,productId,money,from,until,status,createdAt,updatedAt);}
 public UUID id(){return id;} public UUID tenantId(){return tenantId;} public UUID sellableProductId(){return sellableProductId;} public Money money(){return money;} public Instant validFrom(){return validFrom;} public Instant validUntil(){return validUntil;} public PriceStatus status(){return status;} public Instant createdAt(){return createdAt;} public Instant updatedAt(){return updatedAt;}
}
