package com.company.platform.order.api;

import com.company.platform.order.application.OrderService;
import com.company.platform.order.domain.*;
import com.company.platform.order.infrastructure.TenantContextProvider;
import org.springframework.http.*; import org.springframework.security.access.AccessDeniedException; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.security.core.context.SecurityContextHolder; import org.springframework.web.bind.annotation.*;
import java.math.BigDecimal; import java.time.Instant; import java.util.*;

@RestController @RequestMapping("/api/orders") public class OrderController {
 private final OrderService service; private final TenantContextProvider tenant; public OrderController(OrderService service,TenantContextProvider tenant){this.service=service;this.tenant=tenant;}
 public record LineRequest(UUID productId,UUID sellableProductId,int quantity){} public record CreateRequest(UUID customerId,UUID storeId,String currency,List<LineRequest> lines,List<LineRequest> items){} public record MarketplaceCreateRequest(UUID purchaseId,UUID tenantId,UUID storeId,String currency,List<LineRequest> lines){} public record QuantityRequest(int quantity){}
 public record OrderResponse(UUID id,UUID purchaseId,String orderNumber,UUID tenantId,UUID customerId,UUID storeId,String status,String currency,BigDecimal subtotal,BigDecimal total,List<?> lines,Instant createdAt,Instant updatedAt){static OrderResponse of(Order o){return new OrderResponse(o.id(),o.purchaseId(),o.orderNumber().value(),o.tenantId(),o.customerId(),o.storeId(),o.status().name(),o.currency().getCurrencyCode(),o.subtotal().amount(),o.total().amount(),o.items(),o.createdAt(),o.updatedAt());}}
 private UUID currentUser(UUID requested){try{return UUID.fromString(SecurityContextHolder.getContext().getAuthentication().getName());}catch(Exception e){return requested;}}
 private UUID manageableTenant(UUID requested){if(requested==null)throw new IllegalArgumentException("TENANT_REQUIRED");var authentication=SecurityContextHolder.getContext().getAuthentication();boolean platform=authentication!=null&&authentication.getAuthorities().stream().anyMatch(a->a.getAuthority().equals("PLATFORM_ADMIN")||a.getAuthority().equals("ROLE_PLATFORM_ADMIN"));if(!platform&&!requested.equals(tenant.currentTenantId()))throw new AccessDeniedException("TENANT_ACCESS_DENIED");return requested;}
 @PostMapping @ResponseStatus(HttpStatus.CREATED) @PreAuthorize("hasAnyAuthority('ORDER_CREATE','TENANT_OWNER','TENANT_ADMIN','TENANT_MANAGER')") public OrderResponse create(@RequestBody CreateRequest r){List<LineRequest> source=r.lines()!=null?r.lines():r.items();if(source==null)source=List.of();var commands=source.stream().map(x->new OrderService.ItemCommand(x.productId()!=null?x.productId():x.sellableProductId(),null,x.quantity(),null)).toList();return OrderResponse.of(service.create(currentUser(r.customerId()),r.storeId(),Currency.getInstance(r.currency()),commands));}
 @PostMapping("/marketplace") @ResponseStatus(HttpStatus.CREATED) @PreAuthorize("hasAuthority('ORDER_CREATE')") public OrderResponse marketplace(@RequestBody MarketplaceCreateRequest r){List<LineRequest> source=r.lines()==null?List.of():r.lines();var commands=source.stream().map(x->new OrderService.ItemCommand(x.productId()!=null?x.productId():x.sellableProductId(),null,x.quantity(),null)).toList();return OrderResponse.of(service.createForTenant(r.purchaseId(),r.tenantId(),currentUser(null),r.storeId(),Currency.getInstance(r.currency()),commands));}
 @GetMapping("/management") @PreAuthorize("hasAnyAuthority('ORDER_READ','TENANT_OWNER','TENANT_ADMIN','TENANT_MANAGER','PLATFORM_ADMIN','ROLE_PLATFORM_ADMIN')") public List<OrderResponse> management(@RequestParam UUID tenantId,@RequestParam(required=false) OrderStatus status){return service.listForTenant(manageableTenant(tenantId),status).stream().map(OrderResponse::of).toList();}
 @GetMapping("/management/{id}") @PreAuthorize("hasAnyAuthority('ORDER_READ','TENANT_OWNER','TENANT_ADMIN','TENANT_MANAGER','PLATFORM_ADMIN','ROLE_PLATFORM_ADMIN')") public OrderResponse managementGet(@RequestParam UUID tenantId,@PathVariable UUID id){return OrderResponse.of(service.getForTenant(manageableTenant(tenantId),id));}
 @PostMapping("/management/{id}/confirm") @PreAuthorize("hasAnyAuthority('ORDER_CONFIRM','ORDER_UPDATE','TENANT_OWNER','TENANT_ADMIN','TENANT_MANAGER','PLATFORM_ADMIN','ROLE_PLATFORM_ADMIN')") public OrderResponse managementConfirm(@RequestParam UUID tenantId,@PathVariable UUID id){return OrderResponse.of(service.confirmForTenant(manageableTenant(tenantId),id));}
 @PostMapping("/management/{id}/start-processing") @PreAuthorize("hasAnyAuthority('ORDER_UPDATE','TENANT_OWNER','TENANT_ADMIN','TENANT_MANAGER','PLATFORM_ADMIN','ROLE_PLATFORM_ADMIN')") public OrderResponse managementStartProcessing(@RequestParam UUID tenantId,@PathVariable UUID id){return OrderResponse.of(service.startProcessingForTenant(manageableTenant(tenantId),id));}
 @PostMapping("/management/{id}/complete") @PreAuthorize("hasAnyAuthority('ORDER_UPDATE','TENANT_OWNER','TENANT_ADMIN','TENANT_MANAGER','PLATFORM_ADMIN','ROLE_PLATFORM_ADMIN')") public OrderResponse managementComplete(@RequestParam UUID tenantId,@PathVariable UUID id){return OrderResponse.of(service.completeForTenant(manageableTenant(tenantId),id));}
 @PostMapping("/management/{id}/cancel") @PreAuthorize("hasAnyAuthority('ORDER_CANCEL','ORDER_UPDATE','TENANT_OWNER','TENANT_ADMIN','TENANT_MANAGER','PLATFORM_ADMIN','ROLE_PLATFORM_ADMIN')") public OrderResponse managementCancel(@RequestParam UUID tenantId,@PathVariable UUID id){return OrderResponse.of(service.cancelForTenant(manageableTenant(tenantId),id));}
 @GetMapping @PreAuthorize("hasAnyAuthority('ORDER_READ','TENANT_OWNER','TENANT_ADMIN','TENANT_MANAGER')") public List<OrderResponse> list(@RequestParam(required=false) OrderStatus status){return service.list(status).stream().map(OrderResponse::of).toList();}
 @GetMapping("/{id}") @PreAuthorize("hasAnyAuthority('ORDER_READ','TENANT_OWNER','TENANT_ADMIN','TENANT_MANAGER')") public OrderResponse get(@PathVariable UUID id){return OrderResponse.of(service.get(id));}
 @PostMapping("/{id}/lines") @PreAuthorize("hasAnyAuthority('ORDER_UPDATE','ORDER_CREATE','TENANT_OWNER','TENANT_ADMIN','TENANT_MANAGER')") public OrderResponse addLine(@PathVariable UUID id,@RequestBody LineRequest r){return OrderResponse.of(service.addLine(id,r.productId()!=null?r.productId():r.sellableProductId(),r.quantity()));}
 @PatchMapping("/{id}/lines/{lineId}") @PreAuthorize("hasAnyAuthority('ORDER_UPDATE','TENANT_OWNER','TENANT_ADMIN','TENANT_MANAGER')") public OrderResponse updateLine(@PathVariable UUID id,@PathVariable UUID lineId,@RequestBody QuantityRequest r){return OrderResponse.of(service.updateLine(id,lineId,r.quantity()));}
 @DeleteMapping("/{id}/lines/{lineId}") @ResponseStatus(HttpStatus.NO_CONTENT) @PreAuthorize("hasAnyAuthority('ORDER_UPDATE','TENANT_OWNER','TENANT_ADMIN','TENANT_MANAGER')") public void removeLine(@PathVariable UUID id,@PathVariable UUID lineId){service.removeLine(id,lineId);}
 @PostMapping("/{id}/confirm") @PreAuthorize("hasAnyAuthority('ORDER_CONFIRM','ORDER_UPDATE','TENANT_OWNER','TENANT_ADMIN','TENANT_MANAGER')") public OrderResponse confirm(@PathVariable UUID id){return OrderResponse.of(service.confirm(id));}
 @PostMapping("/{id}/cancel") @PreAuthorize("hasAnyAuthority('ORDER_CANCEL','ORDER_UPDATE','TENANT_OWNER','TENANT_ADMIN','TENANT_MANAGER')") public OrderResponse cancel(@PathVariable UUID id){return OrderResponse.of(service.cancel(id));}
}
